drop view if exists "public"."Relation Assertions";

drop view if exists "public"."Relation Verb Assertions";


  create table "public"."Actions" (
    "action_id" bigint generated by default as identity not null,
    "action_name" text not null default ''::text,
    "action_direct_kind" bigint,
    "action_indirect_kind" bigint,
    "action_commands" text[],
    "action_out_of_world" boolean not null default false,
    "action_variables" jsonb
      );


alter table "public"."Actions" enable row level security;


  create table "public"."Rules Master" (
    "rule_id" bigint generated by default as identity not null,
    "rule_name" text not null,
    "rule_in_rulebook" bigint,
    "rule_position_in_rulebook" bigint,
    "rule_basis_entity" bigint,
    "rule_condition" jsonb,
    "rule_contents" jsonb
      );


alter table "public"."Rules Master" enable row level security;

CREATE UNIQUE INDEX "Actions_action_name_key" ON public."Actions" USING btree (action_name);

CREATE UNIQUE INDEX "Actions_pkey" ON public."Actions" USING btree (action_id);

CREATE UNIQUE INDEX "All Kinds_kind_name_key" ON public."All Kinds" USING btree (kind_name);

CREATE UNIQUE INDEX "Relations_relation_name_key" ON public."Relations" USING btree (relation_name);

CREATE UNIQUE INDEX "Rulebooks_rulebook_name_key" ON public."Rulebooks" USING btree (rulebook_name);

CREATE UNIQUE INDEX "Rules Master_pkey" ON public."Rules Master" USING btree (rule_id);

CREATE UNIQUE INDEX "Rules Master_rule_name_key" ON public."Rules Master" USING btree (rule_name);

alter table "public"."Actions" add constraint "Actions_pkey" PRIMARY KEY using index "Actions_pkey";

alter table "public"."Rules Master" add constraint "Rules Master_pkey" PRIMARY KEY using index "Rules Master_pkey";

alter table "public"."Actions" add constraint "Actions_action_direct_kind_fkey" FOREIGN KEY (action_direct_kind) REFERENCES public."All Kinds"(kind_id) ON UPDATE CASCADE not valid;

alter table "public"."Actions" validate constraint "Actions_action_direct_kind_fkey";

alter table "public"."Actions" add constraint "Actions_action_indirect_kind_fkey" FOREIGN KEY (action_indirect_kind) REFERENCES public."All Kinds"(kind_id) ON UPDATE CASCADE not valid;

alter table "public"."Actions" validate constraint "Actions_action_indirect_kind_fkey";

alter table "public"."Actions" add constraint "Actions_action_name_key" UNIQUE using index "Actions_action_name_key";

alter table "public"."All Kinds" add constraint "All Kinds_kind_name_key" UNIQUE using index "All Kinds_kind_name_key";

alter table "public"."Relations" add constraint "Relations_relation_name_key" UNIQUE using index "Relations_relation_name_key";

alter table "public"."Rulebooks" add constraint "Rulebooks_rulebook_name_key" UNIQUE using index "Rulebooks_rulebook_name_key";

alter table "public"."Rules Master" add constraint "Rules Master_rule_in_rulebook_fkey" FOREIGN KEY (rule_in_rulebook) REFERENCES public."Rulebooks"(rulebook_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Rules Master" validate constraint "Rules Master_rule_in_rulebook_fkey";

alter table "public"."Rules Master" add constraint "Rules Master_rule_name_key" UNIQUE using index "Rules Master_rule_name_key";

create or replace view "public"."Action Assertions" as  SELECT (((initcap("Actions".action_name) || ' is an action '::text) ||
        CASE
            WHEN "Actions".action_out_of_world THEN 'out of world'::text
            ELSE ('applying to '::text ||
            CASE
                WHEN ("Actions".action_indirect_kind IS NOT NULL) THEN
                CASE
                    WHEN ("Actions".action_direct_kind = "Actions".action_indirect_kind) THEN ('two '::text || public.pluralize_noun(lower(k.kind_name)))
                    ELSE ((('one '::text || lower(k.kind_name)) || ' and one '::text) || lower(k2.kind_name))
                END
                WHEN ("Actions".action_direct_kind IS NOT NULL) THEN ('one '::text || lower(k.kind_name))
                ELSE 'nothing'::text
            END)
        END) || '.'::text) AS action_assertion,
    "Actions".action_id,
    "Actions".action_name,
    k.kind_name AS action_direct_kind_name,
    k2.kind_name AS action_indirect_kind_name,
    "Actions".action_out_of_world
   FROM ((public."Actions"
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = "Actions".action_direct_kind)))
     LEFT JOIN public."All Kinds" k2 ON ((k2.kind_id = "Actions".action_indirect_kind)));


create or replace view "public"."Relation Assertions" as  SELECT (((((initcap("Relations".relation_name) || ' relates '::text) ||
        CASE
            WHEN ("Relations".relation_type = ANY (ARRAY['one-to-one'::public."relation types", 'one-to-various'::public."relation types", 'one-to-another (symmetric)'::public."relation types"])) THEN ('one '::text || lower(k.kind_name))
            WHEN ("Relations".relation_type = ANY (ARRAY['various-to-one'::public."relation types", 'various-to-various'::public."relation types", 'various-to-each-other (symmetric)'::public."relation types", 'various-to-each-other-in-groups (equivalence)'::public."relation types"])) THEN ('various '::text || public.pluralize_noun(lower(k.kind_name)))
            ELSE NULL::text
        END) || ' to '::text) ||
        CASE
            WHEN ("Relations".relation_type = ANY (ARRAY['one-to-one'::public."relation types", 'various-to-one'::public."relation types", 'one-to-another (symmetric)'::public."relation types"])) THEN ('one '::text || lower(k2.kind_name))
            WHEN ("Relations".relation_type = ANY (ARRAY['one-to-various'::public."relation types", 'various-to-various'::public."relation types", 'various-to-each-other (symmetric)'::public."relation types", 'various-to-each-other-in-groups (equivalence)'::public."relation types"])) THEN ('various '::text || public.pluralize_noun(lower(k2.kind_name)))
            ELSE NULL::text
        END) || '.'::text) AS relation_assertion,
    "Relations".relation_id,
    "Relations".relation_name,
    k.kind_name AS relation_relates_kind_name,
    k2.kind_name AS relation_relates_to_kind_name
   FROM ((public."Relations"
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = "Relations".relation_relates_kind)))
     LEFT JOIN public."All Kinds" k2 ON ((k2.kind_id = "Relations".relation_relates_to_kind)));


create or replace view "public"."Relation Verb Assertions" as  SELECT ((((('The verb '::text || t.individual_verb) || ' means the '::text) || t.marker) || lower(r.relation_name)) || ' relation.'::text) AS relation_verb_assertion,
    r.relation_id,
    r.relation_name,
    r.relation_verb,
    r.relation_reversed_verb
   FROM (public."Relations" r
     CROSS JOIN LATERAL ( SELECT v.marker,
            v.individual_verb
           FROM ( SELECT ''::text AS marker,
                    unnest(r.relation_verb) AS individual_verb
                UNION ALL
                 SELECT 'reversed '::text AS marker,
                    unnest(r.relation_reversed_verb) AS individual_verb) v) t);


grant delete on table "public"."Actions" to "anon";

grant insert on table "public"."Actions" to "anon";

grant references on table "public"."Actions" to "anon";

grant select on table "public"."Actions" to "anon";

grant trigger on table "public"."Actions" to "anon";

grant truncate on table "public"."Actions" to "anon";

grant update on table "public"."Actions" to "anon";

grant delete on table "public"."Actions" to "authenticated";

grant insert on table "public"."Actions" to "authenticated";

grant references on table "public"."Actions" to "authenticated";

grant select on table "public"."Actions" to "authenticated";

grant trigger on table "public"."Actions" to "authenticated";

grant truncate on table "public"."Actions" to "authenticated";

grant update on table "public"."Actions" to "authenticated";

grant delete on table "public"."Actions" to "service_role";

grant insert on table "public"."Actions" to "service_role";

grant references on table "public"."Actions" to "service_role";

grant select on table "public"."Actions" to "service_role";

grant trigger on table "public"."Actions" to "service_role";

grant truncate on table "public"."Actions" to "service_role";

grant update on table "public"."Actions" to "service_role";

grant delete on table "public"."Rules Master" to "anon";

grant insert on table "public"."Rules Master" to "anon";

grant references on table "public"."Rules Master" to "anon";

grant select on table "public"."Rules Master" to "anon";

grant trigger on table "public"."Rules Master" to "anon";

grant truncate on table "public"."Rules Master" to "anon";

grant update on table "public"."Rules Master" to "anon";

grant delete on table "public"."Rules Master" to "authenticated";

grant insert on table "public"."Rules Master" to "authenticated";

grant references on table "public"."Rules Master" to "authenticated";

grant select on table "public"."Rules Master" to "authenticated";

grant trigger on table "public"."Rules Master" to "authenticated";

grant truncate on table "public"."Rules Master" to "authenticated";

grant update on table "public"."Rules Master" to "authenticated";

grant delete on table "public"."Rules Master" to "service_role";

grant insert on table "public"."Rules Master" to "service_role";

grant references on table "public"."Rules Master" to "service_role";

grant select on table "public"."Rules Master" to "service_role";

grant trigger on table "public"."Rules Master" to "service_role";

grant truncate on table "public"."Rules Master" to "service_role";

grant update on table "public"."Rules Master" to "service_role";


  create policy "Enable insert access for all users"
  on "public"."Actions"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable read access for all users"
  on "public"."Actions"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert access for all users"
  on "public"."Relations"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable read access for all users"
  on "public"."Relations"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert access for all users"
  on "public"."Rules Master"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable read access for all users"
  on "public"."Rules Master"
  as permissive
  for select
  to public
using (true);



