create extension if not exists "pg_jsonschema" with schema "extensions";

alter table "public"."All Kinds" drop constraint "All Kinds_parent_kind_id_fkey";

drop view if exists "public"."Action Assertions";

drop view if exists "public"."Kinds of Value";

drop view if exists "public"."Kinds";

drop view if exists "public"."Relation Assertions";

drop view if exists "public"."Relation Verb Assertions";

drop view if exists "public"."Rulebook Assertions";

alter table "public"."Rulebooks" alter column "rulebook_default_outcome" drop default;


  create table "public"."Entities" (
    "entity_id" bigint generated by default as identity not null,
    "entity_of_kind_id" bigint not null default '4'::bigint,
    "entity_name" text not null default ''::text
      );


alter table "public"."Entities" enable row level security;


  create table "public"."Entity-Properties" (
    "entityproperty_property_id" bigint not null,
    "entityproperty_entity_id" bigint not null,
    "entityproperty_initial_value" jsonb
      );


alter table "public"."Entity-Properties" enable row level security;


  create table "public"."Kind-Properties" (
    "kindproperty_property_id" bigint not null,
    "kindproperty_kind_id" bigint not null,
    "kindproperty_initial_value" jsonb,
    "kindproperty_implication" text[]
      );


alter table "public"."Kind-Properties" enable row level security;


  create table "public"."Properties" (
    "property_id" bigint generated by default as identity not null,
    "property_name" text,
    "property_adjective" text,
    "property_opposite_adjective" text,
    "property_kind_id" bigint
      );


alter table "public"."Properties" enable row level security;


  create table "public"."Variables" (
    "variable_id" bigint generated by default as identity not null,
    "variable_of_kind_id" bigint not null default '500'::bigint,
    "variable_name" text not null default ''::text,
    "variable_initial_value" jsonb
      );


alter table "public"."Variables" enable row level security;

alter table "public"."Rulebooks" alter column rulebook_default_outcome type "public"."ruleboook outcomes" using rulebook_default_outcome::text::"public"."ruleboook outcomes";

alter table "public"."Rulebooks" alter column "rulebook_default_outcome" set default 'success'::public."ruleboook outcomes";

alter table "public"."Actions" drop column "action_variables";

alter table "public"."All Kinds" drop column "kind_properties";

alter table "public"."All Kinds" drop column "parent_kind_id";

alter table "public"."All Kinds" add column "kind_parent_id" bigint;

alter table "public"."All Kinds" add column "kind_plural_name" text;

alter table "public"."All Kinds" add column "kind_regtype" regtype;

alter table "public"."All Kinds" alter column "kind_name" drop not null;

alter table "public"."Rulebooks" alter column "rulebook_default_outcome" set default 'no outcome'::public."ruleboook outcomes";

alter table "public"."Rulebooks" alter column "rulebook_default_outcome" drop not null;

CREATE UNIQUE INDEX "All Kinds_kind_plural_name_key" ON public."All Kinds" USING btree (kind_plural_name);

CREATE UNIQUE INDEX "Entities_entity_name_key" ON public."Entities" USING btree (entity_name);

CREATE UNIQUE INDEX "Entities_pkey" ON public."Entities" USING btree (entity_id);

CREATE UNIQUE INDEX "Kind-Properties_pkey" ON public."Kind-Properties" USING btree (kindproperty_property_id, kindproperty_kind_id);

CREATE UNIQUE INDEX "Properties_pkey" ON public."Properties" USING btree (property_id);

CREATE UNIQUE INDEX "Variables_pkey" ON public."Variables" USING btree (variable_id);

CREATE UNIQUE INDEX "Variables_variable_name_key" ON public."Variables" USING btree (variable_name);

CREATE UNIQUE INDEX entity_properties_pkey ON public."Entity-Properties" USING btree (entityproperty_property_id, entityproperty_entity_id);

alter table "public"."Entities" add constraint "Entities_pkey" PRIMARY KEY using index "Entities_pkey";

alter table "public"."Entity-Properties" add constraint "entity_properties_pkey" PRIMARY KEY using index "entity_properties_pkey";

alter table "public"."Kind-Properties" add constraint "Kind-Properties_pkey" PRIMARY KEY using index "Kind-Properties_pkey";

alter table "public"."Properties" add constraint "Properties_pkey" PRIMARY KEY using index "Properties_pkey";

alter table "public"."Variables" add constraint "Variables_pkey" PRIMARY KEY using index "Variables_pkey";

alter table "public"."Actions" add constraint "actions_correct_kinds" CHECK ((((action_direct_kind IS NULL) OR ((action_direct_kind >= 0) AND (action_direct_kind <= 499))) AND ((action_indirect_kind IS NULL) OR ((action_indirect_kind >= 0) AND (action_indirect_kind <= 499))))) not valid;

alter table "public"."Actions" validate constraint "actions_correct_kinds";

alter table "public"."All Kinds" add constraint "All Kinds_kind_parent_id_fkey" FOREIGN KEY (kind_parent_id) REFERENCES public."All Kinds"(kind_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."All Kinds" validate constraint "All Kinds_kind_parent_id_fkey";

alter table "public"."All Kinds" add constraint "All Kinds_kind_plural_name_key" UNIQUE using index "All Kinds_kind_plural_name_key";

alter table "public"."Entities" add constraint "Entities_entity_name_key" UNIQUE using index "Entities_entity_name_key";

alter table "public"."Entities" add constraint "Entities_entity_of_kind_id_fkey" FOREIGN KEY (entity_of_kind_id) REFERENCES public."All Kinds"(kind_id) ON UPDATE CASCADE not valid;

alter table "public"."Entities" validate constraint "Entities_entity_of_kind_id_fkey";

alter table "public"."Entity-Properties" add constraint "Entity-Properties_entityproperty_entity_id_fkey" FOREIGN KEY (entityproperty_entity_id) REFERENCES public."Entities"(entity_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Entity-Properties" validate constraint "Entity-Properties_entityproperty_entity_id_fkey";

alter table "public"."Entity-Properties" add constraint "entity_properties_entityproperty_property_id_fkey" FOREIGN KEY (entityproperty_property_id) REFERENCES public."Properties"(property_id) ON UPDATE CASCADE not valid;

alter table "public"."Entity-Properties" validate constraint "entity_properties_entityproperty_property_id_fkey";

alter table "public"."Kind-Properties" add constraint "Kind-Properties_kindproperty_kind_id_fkey" FOREIGN KEY (kindproperty_kind_id) REFERENCES public."All Kinds"(kind_id) ON UPDATE CASCADE not valid;

alter table "public"."Kind-Properties" validate constraint "Kind-Properties_kindproperty_kind_id_fkey";

alter table "public"."Kind-Properties" add constraint "Kind-Properties_kindproperty_property_id_fkey" FOREIGN KEY (kindproperty_property_id) REFERENCES public."Properties"(property_id) ON UPDATE CASCADE not valid;

alter table "public"."Kind-Properties" validate constraint "Kind-Properties_kindproperty_property_id_fkey";

alter table "public"."Properties" add constraint "Properties_property_kind_id_fkey" FOREIGN KEY (property_kind_id) REFERENCES public."All Kinds"(kind_id) ON UPDATE CASCADE not valid;

alter table "public"."Properties" validate constraint "Properties_property_kind_id_fkey";

alter table "public"."Properties" add constraint "property_adjective_exists" CHECK (((property_opposite_adjective IS NULL) OR (property_adjective IS NOT NULL))) not valid;

alter table "public"."Properties" validate constraint "property_adjective_exists";

alter table "public"."Properties" add constraint "property_kind_or_adjective" CHECK (((property_kind_id IS NOT NULL) OR (property_adjective IS NOT NULL))) not valid;

alter table "public"."Properties" validate constraint "property_kind_or_adjective";

alter table "public"."Variables" add constraint "Variables_variable_name_key" UNIQUE using index "Variables_variable_name_key";

alter table "public"."Variables" add constraint "Variables_variable_of_kind_id_fkey" FOREIGN KEY (variable_of_kind_id) REFERENCES public."All Kinds"(kind_id) ON UPDATE CASCADE not valid;

alter table "public"."Variables" validate constraint "Variables_variable_of_kind_id_fkey";

set check_function_bodies = off;

create or replace view "public"."Variable Assertions" as  SELECT (((('The '::text || v.variable_name) || ' is a '::text) || lower(k.kind_name)) || ' that varies.'::text) AS variable_assertion,
        CASE
            WHEN (v.variable_initial_value IS NOT NULL) THEN (((('The '::text || v.variable_name) || ' is initially '::text) || (jsonb_path_query_first(v.variable_initial_value, '$.*'::jsonpath) ->> 0)) || '.'::text)
            ELSE NULL::text
        END AS variable_initial_value_assertion,
    v.variable_id,
    v.variable_name,
    k.kind_name,
    v.variable_initial_value
   FROM (public."Variables" v
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = v.variable_of_kind_id)));


CREATE OR REPLACE FUNCTION public.get_kind_parents(p_kind_id integer)
 RETURNS TABLE(parent_kind_id integer)
 LANGUAGE sql
AS $function$
  with recursive ancestors as (
    -- start from the direct parent(s)
    select
      ak.kind_parent_id as current_kind_id
    from "All Kinds" ak
    where ak.kind_id = p_kind_id
      and ak.kind_parent_id is not null

    union all

    -- climb upwards: parent of the current node
    select
      ak2.kind_parent_id as current_kind_id
    from "All Kinds" ak2
    join ancestors a
      on ak2.kind_id = a.current_kind_id
    where ak2.kind_parent_id is not null
  )
  select distinct current_kind_id as parent_kind_id
  from ancestors
  order by parent_kind_id;
$function$
;

CREATE OR REPLACE FUNCTION public.kind_of_entity(p_kind_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select exists (
    select 1
    from get_kind_parents(p_kind_id::integer) gp
    join "All Kinds" pk on pk.kind_id = gp.parent_kind_id::bigint
    where pk.kind_name = 'Entity'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.make_list(elements text[], conjunction text DEFAULT 'and'::text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
    list_length INT := array_length(elements, 1);
BEGIN
    -- Handle empty or null arrays
    IF elements IS NULL OR list_length IS NULL OR list_length = 0 THEN
        RETURN '';
    END IF;

    -- Clean conjunction input (remove spaces, lowercase)
    conjunction := lower(trim(conjunction));

    -- Validate conjunction type
    IF conjunction NOT IN ('and', 'or') THEN
        RAISE EXCEPTION 'Conjunction must be either ''and'' or ''or''';
    END IF;

    -- Format based on element count
    CASE list_length
        WHEN 1 THEN 
            RETURN elements[1];
        WHEN 2 THEN 
            RETURN elements[1] || ' ' || conjunction || ' ' || elements[2];
        ELSE 
            -- Uses the Oxford Comma format
            RETURN array_to_string(elements[1 : list_length - 1], ', ') || ', ' || conjunction || ' ' || elements[list_length];
    END CASE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.trg_kind_properties_validate_implications()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  imp text;
  new_base_prop_adjective text;
  all_ok boolean;
begin
  if NEW.kindproperty_implication is null then
    return NEW;
  end if;

  select p.property_adjective
  into new_base_prop_adjective
  from public."Properties" p
  where p.property_id = NEW.kindproperty_property_id;

  if new_base_prop_adjective is null then
    raise exception
      'Invalid insert/update: Properties.property_adjective must be non-null for kindproperty_property_id=%',
      NEW.kindproperty_property_id;
  end if;

  if array_length(NEW.kindproperty_implication, 1) is null then
    return NEW;
  end if;

  all_ok := true;

  foreach imp in array NEW.kindproperty_implication
  loop
    if imp is null then
      all_ok := false;
      exit;
    end if;

    if not exists (
      select 1
      from public."Kind-Properties" kp2
      join public."Properties" p2
        on p2.property_id = kp2.kindproperty_property_id
      where kp2.kindproperty_kind_id = NEW.kindproperty_kind_id
        and kp2.kindproperty_property_id <> NEW.kindproperty_property_id
        and (
          imp = p2.property_adjective
          or imp = p2.property_opposite_adjective
          or (
            p2.property_opposite_adjective is null
            and imp = ('not ' || p2.property_adjective)
          )
        )
    ) then
      all_ok := false;
      exit;
    end if;
  end loop;

  if all_ok then
    return NEW;
  end if;

  raise exception
    'Invalid insert/update: one or more kindproperty_implication values must match property_adjective or property_opposite_adjective (or "not "||property_adjective when opposite is null) from a different Kind-Properties row with same kindproperty_kind_id=%',
    NEW.kindproperty_kind_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_jsonb_key_matches_kind()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$DECLARE
  v_kind_id_col     text := TG_ARGV[0]; -- Name of the column holding the kind_id (or property_id, in this special case)
  v_jsonb_col       text := TG_ARGV[1]; -- Name of the column holding the jsonb data
  v_kind_id_val     int;
  v_jsonb_val       jsonb;
  v_kind_name_key   text;
  v_key_count       int;
BEGIN
  -- 1. Use RECORD features to dynamically extract values from the row
  EXECUTE format('SELECT ($1).%I, ($1).%I', v_kind_id_col, v_jsonb_col)
  USING NEW
  INTO v_kind_id_val, v_jsonb_val;

  -- EARLY RETURN: Safely allow structural null values or unassigned values to pass through
  if v_jsonb_val is null or v_jsonb_val = 'null'::jsonb or v_kind_id_val is null then
    return NEW;
  end if;

  -- NEW: If the column name contains "property_id", resolve it to property_kind_id first
  IF v_kind_id_col ILIKE '%property_id%' THEN
    SELECT p."property_kind_id"
    INTO v_kind_id_val
    FROM "Properties" p
    WHERE p."property_id" = v_kind_id_val;

    -- Fail if the linked property data does not exist
    IF v_kind_id_val IS NULL THEN
      return new;
    END IF;
  END IF;

  -- 2. Fetch and lowercase the kind_name from "All Kinds" using the (resolved) kind id
  SELECT lower(k.kind_name) INTO v_kind_name_key 
  FROM "All Kinds" k 
  WHERE k.kind_id = v_kind_id_val;

  -- 3. Fail if the linked kind data does not exist
  IF v_kind_name_key IS NULL THEN
    RAISE EXCEPTION 'Foreign key % (% = %) not found in "All Kinds"', 
                    v_kind_id_col, v_kind_id_col, v_kind_id_val;
  END IF;

  -- 4. Check structural rules: must be a valid JSON object
  IF jsonb_typeof(v_jsonb_val) != 'object' THEN
    RAISE EXCEPTION 'Column % must be a valid JSON object', v_jsonb_col;
  END IF;

  -- 5. Count the number of unique keys at the root of the JSON object
  SELECT count(*) INTO v_key_count 
  FROM jsonb_object_keys(v_jsonb_val);

 -- 6. Enforce that the JSON object's single key matches:
  --    - the configured kind name, OR
  --    - any child kind of that kind
  IF v_key_count != 1 THEN
    RAISE EXCEPTION 'JSON object in % must contain exactly one key named "%"', 
                    v_jsonb_col, v_kind_name_key;
  END IF;

  -- Get the single key (root JSON key)
  SELECT lower(j.key)
  INTO v_kind_name_key
  FROM jsonb_object_keys(v_jsonb_val) AS j(key)
  LIMIT 1;

  -- Allow exact match
  IF v_kind_name_key = (
      SELECT lower(k.kind_name)
      FROM "All Kinds" k
      WHERE k.kind_id = v_kind_id_val
  ) THEN
    RETURN NEW;
  END IF;

  -- Otherwise, treat the JSON key as a kind_name, resolve it to a kind_id
  DECLARE
    v_json_kind_id int;
  BEGIN
    SELECT k.kind_id
    INTO v_json_kind_id
    FROM "All Kinds" k
    WHERE lower(k.kind_name) = v_kind_name_key;

    IF v_json_kind_id IS NULL THEN
      RAISE EXCEPTION 'JSON key "%" in % does not match any kind_name in "All Kinds"', 
        v_kind_name_key, v_jsonb_col;
    END IF;

    -- Check whether the configured kind is a parent (ancestor) of the JSON key's kind
    IF NOT EXISTS (
      SELECT 1
      FROM get_kind_parents(v_json_kind_id::integer) gp
      WHERE gp.parent_kind_id::int = v_kind_id_val
    ) THEN
      RAISE EXCEPTION
        'JSON object in % must contain key "%" or a child kind of that kind. Got "%".',
        v_jsonb_col,
        (SELECT lower(k.kind_name) FROM "All Kinds" k WHERE k.kind_id = v_kind_id_val),
        v_kind_name_key;
    END IF;
  END;

  RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.validate_jsonb_value_matches_type()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$declare 
  v_fk_col_name   text := TG_ARGV[0]; 
  v_jsonb_col     text := TG_ARGV[1]; 

  v_fk_val        int;       
  v_outer_json    jsonb;
  v_target_type   regtype;
  v_json_kind_id  bigint;
  
  -- Unwrapped single-object components
  v_inner_key     text;
  v_inner_jsonb   jsonb;
  v_inner_type    text;
  v_txt_val       text;

  -- NEW: for the property_kind_id IS NULL fallback
  v_property_adjective         text;
  v_property_opposite_adjective text;
begin 
  -- 1. Extract the raw foreign key value and the outer JSON wrapper from the row
  execute format('select ($1).%I, ($1).%I', v_fk_col_name, v_jsonb_col) 
    using NEW 
    into v_fk_val, v_outer_json;

  -- If JSON itself is empty/unassigned, let it through
  if v_outer_json is null or v_outer_json = 'null'::jsonb then
    return NEW;
  end if;

  -- 1.5 NEW: If the argument column name contains "property_id", resolve it to property_kind_id first.
  --       If property_kind_id is NULL, run the alternative adjective validation (instead of returning NEW).
  if v_fk_col_name ILIKE '%property_id%' then
    declare
      v_property_kind_id int;
    begin
      select p."property_kind_id"
      into v_property_kind_id
      from "Properties" p
      where p."property_id" = v_fk_val;

    if v_property_kind_id is null then
        -- Fetch adjectives for fallback matching
        select p."property_adjective", p."property_opposite_adjective"
        into v_property_adjective, v_property_opposite_adjective
        from "Properties" p
        where p."property_id" = v_fk_val;

        -- JSON must be a JSON string scalar (text in quotes)
        if jsonb_typeof(v_outer_json) <> 'string' then
          raise exception 'Data rejection on table "%": Column "%" expects a quoted text JSON string (e.g. "value"), but received %.',
            TG_TABLE_NAME, v_jsonb_col, jsonb_typeof(v_outer_json);
        end if;

        v_txt_val := v_outer_json #>> '{}'; -- unquoted text

        -- property_adjective must exist (per your rule)
        if v_property_adjective is null then
          raise exception 'Data rejection on table "%": Properties.property_adjective is NULL for property_id=%.',
            TG_TABLE_NAME, v_fk_val;
        end if;

        -- Acceptable values:
        -- 1) property_adjective always
        -- 2) property_opposite_adjective if not null
        -- 3) otherwise "not " || property_adjective
        if v_txt_val = v_property_adjective then
          return NEW;
        end if;

        if v_property_opposite_adjective is not null and v_txt_val = v_property_opposite_adjective then
          return NEW;
        end if;

        if v_property_opposite_adjective is null and v_txt_val = ('not ' || v_property_adjective) then
          return NEW;
        end if;

        raise exception
          'Data rejection on table "%": Column "%" value "%" must match "%"', 
          TG_TABLE_NAME, v_jsonb_col, v_txt_val, v_property_adjective;
      end if;

      -- property_kind_id exists => proceed normally using v_fk_val as the kind_id lookup key
      -- (so we set v_fk_val to property_kind_id for the remainder of the function)
      v_fk_val := v_property_kind_id;
    end;
  end if;

  -- 2. Fetch the expected database column type from the kinds lookup table
  select kind_regtype::regtype into v_target_type 
  from "All Kinds"
  where kind_id = v_fk_val;

  if v_target_type is null then 
    return NEW; 
  end if;

  -- 3. UNWRAP THE SINGLE OBJECT: Extract the single key and its inner jsonb value directly
  if jsonb_typeof(v_outer_json) != 'object' then
    raise exception 'Data rejection on table "%": Column "%" expects a JSON object with exactly one key for non-null kind validation.',
      TG_TABLE_NAME, v_jsonb_col;
  end if;

  select key, value into v_inner_key, v_inner_jsonb 
  from jsonb_each(v_outer_json) 
  limit 1;

  -- 4. Gather accurate types for the inner payload content
  v_inner_type := jsonb_typeof(v_inner_jsonb);
  v_txt_val    := v_inner_jsonb #>> '{}';

-- If the configured kind is "under Entity", ensure v_txt_val exists in Entities
-- and that it belongs to the kind that was actually specified by the JSON key.
if public.kind_of_entity(v_fk_val::integer) then
  -- Convert the JSON object's single key (kind_name) -> kind_id
  select k.kind_id::bigint
  into v_json_kind_id
  from "All Kinds" k
  where lower(k.kind_name) = v_inner_key;

  if v_json_kind_id is null then
    raise exception
      'Data rejection on table "%": Key "%" is not a recognized kind_name in "All Kinds".',
      TG_TABLE_NAME, v_inner_key;
  end if;

  -- Enforce string scalar for entity_name
  if v_inner_type is distinct from 'string' then
    raise exception
      'Data rejection on table "%": Key "%" expects an entity-name string (JSON string) for Entity-backed kinds, but received %.',
      TG_TABLE_NAME, v_inner_key, v_inner_type;
  end if;

  -- Validate entity belongs to the *kind from the JSON key*
  if not exists (
    select 1
    from "Entities" e
    where e.entity_name = v_txt_val
      and e.entity_of_kind_id = v_json_kind_id
  ) then
    raise exception
      'Data rejection on table "%": Key "%" value "%" is not a valid Entities.entity_name for entity_of_kind_id=% (kind taken from JSON key).',
      TG_TABLE_NAME, v_inner_key, v_txt_val, v_json_kind_id;
  end if;
end if;

  -- 5. THE STRICT RULE: Validate text-targeted types
  if v_target_type in ('text'::regtype, 'character varying'::regtype, 'character'::regtype) then
    if v_inner_type in ('number', 'boolean') then
      raise exception 'Data rejection on table "%": The key "%" expects a text value, so its value must be wrapped in double quotes. Received an unquoted % instead.',
        TG_TABLE_NAME, v_inner_key, v_inner_type;
    end if;
  end if;

  -- 6. Perform the dynamic validation cast check against the database target type
  begin
    execute format('select %L::%s', v_txt_val, v_target_type);
  exception 
    when others then
      raise exception 'Data rejection on table "%": Key "%" value (%) cannot be safely cast to the configured database type "%".', 
        TG_TABLE_NAME, v_inner_key, v_outer_json, v_target_type;
  end;

  return NEW;
end;$function$
;

create or replace view "public"."Action Assertions" as  SELECT (((initcap("Actions".action_name) || ' is an action '::text) ||
        CASE
            WHEN "Actions".action_out_of_world THEN 'out of world'::text
            ELSE ('applying to '::text ||
            CASE
                WHEN ("Actions".action_indirect_kind IS NOT NULL) THEN
                CASE
                    WHEN ("Actions".action_direct_kind = "Actions".action_indirect_kind) THEN ('two '::text || public.pluralize_noun(lower(k.kind_name)))
                    ELSE ((('one '::text || lower(k.kind_name)) || ' and one '::text) || lower(k2.kind_name))
                END
                WHEN ("Actions".action_direct_kind IS NOT NULL) THEN ('one '::text || lower(k.kind_name))
                ELSE 'nothing'::text
            END)
        END) || '.'::text) AS action_assertion,
    "Actions".action_id,
    "Actions".action_name,
    k.kind_name AS action_direct_kind_name,
    k2.kind_name AS action_indirect_kind_name,
    "Actions".action_out_of_world
   FROM ((public."Actions"
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = "Actions".action_direct_kind)))
     LEFT JOIN public."All Kinds" k2 ON ((k2.kind_id = "Actions".action_indirect_kind)));


create or replace view "public"."Kinds of Value" as  SELECT (((((initcap(public.get_indefinite_article(a.kind_name)) || ' '::text) || lower(a.kind_name)) || ' is a kind of '::text) || lower(k.kind_name)) || '.'::text) AS kind_assertion,
    a.kind_id,
    a.kind_name,
    k.kind_name AS parent_kind_name
   FROM (public."All Kinds" a
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = a.kind_parent_id)))
  WHERE ((public.kind_of_entity(a.kind_id) = false) AND (a.kind_name <> 'Entity'::text) AND (a.kind_name <> 'Value'::text));


create or replace view "public"."Kinds" as  SELECT (((((initcap(public.get_indefinite_article(a.kind_name)) || ' '::text) || lower(a.kind_name)) || ' is a kind of '::text) || lower(k.kind_name)) || '.'::text) AS kind_assertion,
    a.kind_id,
    a.kind_name,
    k.kind_name AS parent_kind_name
   FROM (public."All Kinds" a
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = a.kind_parent_id)))
  WHERE (public.kind_of_entity(a.kind_id) = true);


create or replace view "public"."Relation Assertions" as  SELECT (((((initcap("Relations".relation_name) || ' relates '::text) ||
        CASE
            WHEN ("Relations".relation_type = ANY (ARRAY['one-to-one'::public."relation types", 'one-to-various'::public."relation types", 'one-to-another (symmetric)'::public."relation types"])) THEN ('one '::text || lower(k.kind_name))
            WHEN ("Relations".relation_type = ANY (ARRAY['various-to-one'::public."relation types", 'various-to-various'::public."relation types", 'various-to-each-other (symmetric)'::public."relation types", 'various-to-each-other-in-groups (equivalence)'::public."relation types"])) THEN ('various '::text || public.pluralize_noun(lower(k.kind_name)))
            ELSE NULL::text
        END) || ' to '::text) ||
        CASE
            WHEN ("Relations".relation_type = ANY (ARRAY['one-to-one'::public."relation types", 'various-to-one'::public."relation types", 'one-to-another (symmetric)'::public."relation types"])) THEN ('one '::text || lower(k2.kind_name))
            WHEN ("Relations".relation_type = ANY (ARRAY['one-to-various'::public."relation types", 'various-to-various'::public."relation types", 'various-to-each-other (symmetric)'::public."relation types", 'various-to-each-other-in-groups (equivalence)'::public."relation types"])) THEN ('various '::text || public.pluralize_noun(lower(k2.kind_name)))
            ELSE NULL::text
        END) || '.'::text) AS relation_assertion,
    "Relations".relation_id,
    "Relations".relation_name,
    k.kind_name AS relation_relates_kind_name,
    k2.kind_name AS relation_relates_to_kind_name
   FROM ((public."Relations"
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = "Relations".relation_relates_kind)))
     LEFT JOIN public."All Kinds" k2 ON ((k2.kind_id = "Relations".relation_relates_to_kind)));


create or replace view "public"."Relation Verb Assertions" as  SELECT ((((('The verb '::text || t.individual_verb) || ' means the '::text) || t.marker) || lower(r.relation_name)) || ' relation.'::text) AS relation_verb_assertion,
    r.relation_id,
    r.relation_name,
    r.relation_verb,
    r.relation_reversed_verb
   FROM (public."Relations" r
     CROSS JOIN LATERAL ( SELECT v.marker,
            v.individual_verb
           FROM ( SELECT ''::text AS marker,
                    unnest(r.relation_verb) AS individual_verb
                UNION ALL
                 SELECT 'reversed '::text AS marker,
                    unnest(r.relation_reversed_verb) AS individual_verb) v) t);


create or replace view "public"."Rulebook Assertions" as  SELECT (((((((((("Rulebooks".rulebook_name || ' rules is '::text) ||
        CASE
            WHEN ("Rulebooks".rulebook_basis IS NOT NULL) THEN (((public.get_indefinite_article(k.kind_name) || ' '::text) || lower(k.kind_name)) || ' based '::text)
            ELSE 'a '::text
        END) || 'rulebook'::text) ||
        CASE
            WHEN ("Rulebooks".rulebook_result_kind IS NOT NULL) THEN (((' producing '::text || public.get_indefinite_article(k2.kind_name)) || ' '::text) || lower(k2.kind_name))
            ELSE ''::text
        END) ||
        CASE
            WHEN (("Rulebooks".rulebook_named_outcomes_success IS NOT NULL) OR ("Rulebooks".rulebook_named_outcomes_failure IS NOT NULL)) THEN ' with outcomes '::text
            ELSE ''::text
        END) ||
        CASE
            WHEN ("Rulebooks".rulebook_named_outcomes_success IS NOT NULL) THEN ((array_to_string("Rulebooks".rulebook_named_outcomes_success, ', '::text) || ' (success'::text) ||
            CASE
                WHEN ("Rulebooks".rulebook_default_outcome = 'success'::public."ruleboook outcomes") THEN ' - the default)'::text
                ELSE ')'::text
            END)
            ELSE ''::text
        END) ||
        CASE
            WHEN (("Rulebooks".rulebook_named_outcomes_success && "Rulebooks".rulebook_named_outcomes_failure) IS NOT NULL) THEN ' and '::text
            ELSE ''::text
        END) ||
        CASE
            WHEN ("Rulebooks".rulebook_named_outcomes_failure IS NOT NULL) THEN ((array_to_string("Rulebooks".rulebook_named_outcomes_failure, ', '::text) || ' (failure'::text) ||
            CASE
                WHEN ("Rulebooks".rulebook_default_outcome = 'failure'::public."ruleboook outcomes") THEN ' - the default)'::text
                ELSE ')'::text
            END)
            ELSE ''::text
        END) ||
        CASE
            WHEN ("Rulebooks".rulebook_default_outcome <> 'no outcome'::public."ruleboook outcomes") THEN (' with default outcome '::text || "Rulebooks".rulebook_default_outcome)
            ELSE ''::text
        END) || '.'::text) AS rulebook_assertion,
    "Rulebooks".rulebook_id,
    "Rulebooks".rulebook_name,
    k.kind_name AS rulebook_basis_name,
    k2.kind_name AS rulebook_result_kind_name,
    "Rulebooks".rulebook_named_outcomes_success,
    "Rulebooks".rulebook_named_outcomes_failure,
    "Rulebooks".rulebook_default_outcome
   FROM ((public."Rulebooks"
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = "Rulebooks".rulebook_basis)))
     LEFT JOIN public."All Kinds" k2 ON ((k2.kind_id = "Rulebooks".rulebook_result_kind)));


create or replace view "public"."Entity Assertions" as  SELECT ((((((('The '::text || e.entity_name) || ' is '::text) ||
        CASE
            WHEN (eop.entity_either_or_properties IS NOT NULL) THEN ((public.get_indefinite_article(eop.entity_either_or_properties) || ' '::text) || eop.entity_either_or_properties)
            ELSE ''::text
        END) || ' '::text) || lower(k.kind_name)) ||
        CASE
            WHEN (np.entity_named_properties IS NOT NULL) THEN (' with '::text || ( SELECT string_agg(format('%s %s'::text, each_props.npl_key, each_props.npl_value), ', '::text) AS string_agg
               FROM jsonb_each(np.entity_named_properties) each_props(npl_key, npl_value)))
            ELSE ''::text
        END) || '.'::text) AS entity_assertion_with_properties,
    e.entity_id,
    e.entity_name,
    k.kind_name AS entity_of_kind_name,
    COALESCE(( WITH entity_props AS (
                 SELECT ep.entityproperty_property_id AS property_id,
                    ep.entityproperty_initial_value AS initial_value
                   FROM public."Entity-Properties" ep
                  WHERE (ep.entityproperty_entity_id = e.entity_id)
                ), ancestor_kinds AS (
                 SELECT (pk.parent_kind_id)::bigint AS kind_id
                   FROM public.get_kind_parents((e.entity_of_kind_id)::integer) pk(parent_kind_id)
                ), all_kinds_with_depth AS (
                 SELECT e.entity_of_kind_id AS kind_id,
                    0 AS depth
                UNION ALL
                 SELECT ak.kind_id,
                    ak.depth
                   FROM ( SELECT a.kind_id,
                            min(a.depth) AS depth
                           FROM ( WITH RECURSIVE chain(kind_id, depth) AS (
 SELECT e.entity_of_kind_id,
    0 AS "?column?"
UNION ALL
 SELECT ak2.kind_parent_id,
    (chain_1.depth + 1)
   FROM (public."All Kinds" ak2
     JOIN chain chain_1 ON ((ak2.kind_id = chain_1.kind_id)))
  WHERE (ak2.kind_parent_id IS NOT NULL)
)
                                 SELECT chain.kind_id,
                                    chain.depth
                                   FROM chain) a
                          GROUP BY a.kind_id) ak
                  WHERE (ak.kind_id IN ( SELECT ancestor_kinds.kind_id
                           FROM ancestor_kinds))
                ), kind_props AS (
                 SELECT kp.kindproperty_property_id AS property_id,
                    kp.kindproperty_initial_value AS initial_value,
                    akw.depth
                   FROM (public."Kind-Properties" kp
                     JOIN all_kinds_with_depth akw ON ((akw.kind_id = kp.kindproperty_kind_id)))
                ), nearest_kind_props AS (
                 SELECT DISTINCT ON (kind_props.property_id) kind_props.property_id,
                    kind_props.initial_value
                   FROM kind_props
                  ORDER BY kind_props.property_id, kind_props.depth
                ), merged AS (
                 SELECT entity_props.property_id,
                    entity_props.initial_value
                   FROM entity_props
                UNION ALL
                 SELECT nkp.property_id,
                    nkp.initial_value
                   FROM nearest_kind_props nkp
                  WHERE (NOT (EXISTS ( SELECT 1
                           FROM entity_props ep
                          WHERE (ep.property_id = nkp.property_id))))
                ), with_props_text AS (
                 SELECT m.property_id,
                    m.initial_value,
                    p.property_adjective,
                    p.property_name,
                        CASE
                            WHEN (p.property_name IS NOT NULL) THEN p.property_name
                            ELSE ('property_'::text || (m.property_id)::text)
                        END AS json_key,
                        CASE
                            WHEN (m.initial_value IS NOT NULL) THEN m.initial_value
                            WHEN (p.property_adjective IS NOT NULL) THEN to_jsonb(('not '::text || p.property_adjective))
                            ELSE NULL::jsonb
                        END AS resolved_initial_value
                   FROM (merged m
                     LEFT JOIN public."Properties" p ON ((p.property_id = m.property_id)))
                )
         SELECT jsonb_object_agg(wpt.json_key, wpt.resolved_initial_value) AS jsonb_object_agg
           FROM with_props_text wpt), '{}'::jsonb) AS entity_properties_index
   FROM (((public."Entities" e
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = e.entity_of_kind_id)))
     LEFT JOIN LATERAL ( SELECT string_agg((ep.entityproperty_initial_value #>> '{}'::text[]), ' '::text) AS entity_either_or_properties
           FROM (public."Entity-Properties" ep
             JOIN public."Properties" p ON ((p.property_id = ep.entityproperty_property_id)))
          WHERE ((ep.entityproperty_entity_id = e.entity_id) AND (p.property_adjective IS NOT NULL))) eop ON (true))
     LEFT JOIN LATERAL ( SELECT jsonb_object_agg(p.property_name, ( SELECT jsonb_each.value
                   FROM jsonb_each(ep.entityproperty_initial_value) jsonb_each(key, value)
                 LIMIT 1)) AS entity_named_properties
           FROM (public."Entity-Properties" ep
             JOIN public."Properties" p ON ((p.property_id = ep.entityproperty_property_id)))
          WHERE ((ep.entityproperty_entity_id = e.entity_id) AND (p.property_name IS NOT NULL))) np ON (true));


create or replace view "public"."Kind-Property Assertions" as  SELECT
        CASE
            WHEN (EXISTS ( SELECT 1
               FROM (public.get_kind_parents((k.kind_id)::integer) gp(parent_kind_id)
                 JOIN public."Kind-Properties" kp_parent ON ((kp_parent.kindproperty_kind_id = gp.parent_kind_id)))
              WHERE (kp_parent.kindproperty_property_id = p.property_id))) THEN NULL::text
            ELSE ((((initcap(public.get_indefinite_article(k.kind_name)) || ' '::text) || lower(k.kind_name)) ||
            CASE
                WHEN (p.property_kind_id IS NULL) THEN ((' can be '::text || lower(p.property_adjective)) ||
                CASE
                    WHEN (p.property_opposite_adjective IS NOT NULL) THEN (' or '::text || p.property_opposite_adjective)
                    ELSE ''::text
                END)
                ELSE ((((' has '::text || public.get_indefinite_article(k2.kind_name)) || ' '::text) || lower(k2.kind_name)) ||
                CASE
                    WHEN (p.property_name IS NOT NULL) THEN ((' called '::text ||
                    CASE
                        WHEN public.kind_of_entity(p.property_kind_id) THEN (public.get_indefinite_article(p.property_name) || ' '::text)
                        ELSE ''::text
                    END) || lower(p.property_name))
                    ELSE ''::text
                END)
            END) || '.'::text)
        END AS kindproperty_assertion,
        CASE
            WHEN (kp.kindproperty_initial_value IS NOT NULL) THEN
            CASE
                WHEN (pv.key = 'text'::text) THEN (((((((('The '::text || p.property_name) || ' of '::text) || public.get_indefinite_article(k.kind_name)) || ' '::text) || lower(k.kind_name)) || ' is usually "'::text) || pv.value) || '".'::text)
                WHEN (pv.key = 'property'::text) THEN (((((initcap(public.get_indefinite_article(k.kind_name)) || ' '::text) || lower(k.kind_name)) || ' is usually '::text) || pv.value) || '.'::text)
                ELSE (((((((('The '::text || p.property_name) || ' of '::text) || public.get_indefinite_article(k.kind_name)) || ' '::text) || lower(k.kind_name)) || ' is usually '::text) || pv.value) || '.'::text)
            END
            ELSE NULL::text
        END AS kindproperty_initial_value_assertion,
        CASE
            WHEN (kp.kindproperty_implication IS NOT NULL) THEN ( SELECT string_agg((((
                    CASE
                        WHEN (k.kind_name <> 'Thing'::text) THEN ((((initcap(public.get_indefinite_article(p.property_adjective)) || ' '::text) || p.property_adjective) || ' '::text) || lower(k.kind_name))
                        ELSE initcap(p.property_adjective)
                    END || ' is usually '::text) || imp.imp_value) || '.'::text), ' '::text) AS string_agg
               FROM unnest(kp.kindproperty_implication) imp(imp_value)
              WHERE (imp.imp_value IS NOT NULL))
            ELSE NULL::text
        END AS kindproperty_implication_assertion,
    p.property_id,
    k.kind_name AS property_of_kind_name,
    p.property_name,
    k2.kind_name AS property_kind_name,
    p.property_adjective,
    p.property_opposite_adjective,
    kp.kindproperty_initial_value
   FROM ((((public."Kind-Properties" kp
     LEFT JOIN public."All Kinds" k ON ((k.kind_id = kp.kindproperty_kind_id)))
     LEFT JOIN public."Properties" p ON ((p.property_id = kp.kindproperty_property_id)))
     LEFT JOIN public."All Kinds" k2 ON ((k2.kind_id = p.property_kind_id)))
     LEFT JOIN LATERAL ( SELECT jsonb_each_text.key,
            jsonb_each_text.value
           FROM jsonb_each_text(
                CASE
                    WHEN (jsonb_typeof(kp.kindproperty_initial_value) = 'object'::text) THEN kp.kindproperty_initial_value
                    ELSE jsonb_build_object('property', kp.kindproperty_initial_value)
                END) jsonb_each_text(key, value)) pv(key, value) ON (true));


grant delete on table "public"."Entities" to "anon";

grant insert on table "public"."Entities" to "anon";

grant references on table "public"."Entities" to "anon";

grant select on table "public"."Entities" to "anon";

grant trigger on table "public"."Entities" to "anon";

grant truncate on table "public"."Entities" to "anon";

grant update on table "public"."Entities" to "anon";

grant delete on table "public"."Entities" to "authenticated";

grant insert on table "public"."Entities" to "authenticated";

grant references on table "public"."Entities" to "authenticated";

grant select on table "public"."Entities" to "authenticated";

grant trigger on table "public"."Entities" to "authenticated";

grant truncate on table "public"."Entities" to "authenticated";

grant update on table "public"."Entities" to "authenticated";

grant delete on table "public"."Entities" to "service_role";

grant insert on table "public"."Entities" to "service_role";

grant references on table "public"."Entities" to "service_role";

grant select on table "public"."Entities" to "service_role";

grant trigger on table "public"."Entities" to "service_role";

grant truncate on table "public"."Entities" to "service_role";

grant update on table "public"."Entities" to "service_role";

grant delete on table "public"."Entity-Properties" to "anon";

grant insert on table "public"."Entity-Properties" to "anon";

grant references on table "public"."Entity-Properties" to "anon";

grant select on table "public"."Entity-Properties" to "anon";

grant trigger on table "public"."Entity-Properties" to "anon";

grant truncate on table "public"."Entity-Properties" to "anon";

grant update on table "public"."Entity-Properties" to "anon";

grant delete on table "public"."Entity-Properties" to "authenticated";

grant insert on table "public"."Entity-Properties" to "authenticated";

grant references on table "public"."Entity-Properties" to "authenticated";

grant select on table "public"."Entity-Properties" to "authenticated";

grant trigger on table "public"."Entity-Properties" to "authenticated";

grant truncate on table "public"."Entity-Properties" to "authenticated";

grant update on table "public"."Entity-Properties" to "authenticated";

grant delete on table "public"."Entity-Properties" to "service_role";

grant insert on table "public"."Entity-Properties" to "service_role";

grant references on table "public"."Entity-Properties" to "service_role";

grant select on table "public"."Entity-Properties" to "service_role";

grant trigger on table "public"."Entity-Properties" to "service_role";

grant truncate on table "public"."Entity-Properties" to "service_role";

grant update on table "public"."Entity-Properties" to "service_role";

grant delete on table "public"."Kind-Properties" to "anon";

grant insert on table "public"."Kind-Properties" to "anon";

grant references on table "public"."Kind-Properties" to "anon";

grant select on table "public"."Kind-Properties" to "anon";

grant trigger on table "public"."Kind-Properties" to "anon";

grant truncate on table "public"."Kind-Properties" to "anon";

grant update on table "public"."Kind-Properties" to "anon";

grant delete on table "public"."Kind-Properties" to "authenticated";

grant insert on table "public"."Kind-Properties" to "authenticated";

grant references on table "public"."Kind-Properties" to "authenticated";

grant select on table "public"."Kind-Properties" to "authenticated";

grant trigger on table "public"."Kind-Properties" to "authenticated";

grant truncate on table "public"."Kind-Properties" to "authenticated";

grant update on table "public"."Kind-Properties" to "authenticated";

grant delete on table "public"."Kind-Properties" to "service_role";

grant insert on table "public"."Kind-Properties" to "service_role";

grant references on table "public"."Kind-Properties" to "service_role";

grant select on table "public"."Kind-Properties" to "service_role";

grant trigger on table "public"."Kind-Properties" to "service_role";

grant truncate on table "public"."Kind-Properties" to "service_role";

grant update on table "public"."Kind-Properties" to "service_role";

grant delete on table "public"."Properties" to "anon";

grant insert on table "public"."Properties" to "anon";

grant references on table "public"."Properties" to "anon";

grant select on table "public"."Properties" to "anon";

grant trigger on table "public"."Properties" to "anon";

grant truncate on table "public"."Properties" to "anon";

grant update on table "public"."Properties" to "anon";

grant delete on table "public"."Properties" to "authenticated";

grant insert on table "public"."Properties" to "authenticated";

grant references on table "public"."Properties" to "authenticated";

grant select on table "public"."Properties" to "authenticated";

grant trigger on table "public"."Properties" to "authenticated";

grant truncate on table "public"."Properties" to "authenticated";

grant update on table "public"."Properties" to "authenticated";

grant delete on table "public"."Properties" to "service_role";

grant insert on table "public"."Properties" to "service_role";

grant references on table "public"."Properties" to "service_role";

grant select on table "public"."Properties" to "service_role";

grant trigger on table "public"."Properties" to "service_role";

grant truncate on table "public"."Properties" to "service_role";

grant update on table "public"."Properties" to "service_role";

grant delete on table "public"."Variables" to "anon";

grant insert on table "public"."Variables" to "anon";

grant references on table "public"."Variables" to "anon";

grant select on table "public"."Variables" to "anon";

grant trigger on table "public"."Variables" to "anon";

grant truncate on table "public"."Variables" to "anon";

grant update on table "public"."Variables" to "anon";

grant delete on table "public"."Variables" to "authenticated";

grant insert on table "public"."Variables" to "authenticated";

grant references on table "public"."Variables" to "authenticated";

grant select on table "public"."Variables" to "authenticated";

grant trigger on table "public"."Variables" to "authenticated";

grant truncate on table "public"."Variables" to "authenticated";

grant update on table "public"."Variables" to "authenticated";

grant delete on table "public"."Variables" to "service_role";

grant insert on table "public"."Variables" to "service_role";

grant references on table "public"."Variables" to "service_role";

grant select on table "public"."Variables" to "service_role";

grant trigger on table "public"."Variables" to "service_role";

grant truncate on table "public"."Variables" to "service_role";

grant update on table "public"."Variables" to "service_role";


  create policy "Enable read access for all users"
  on "public"."Entities"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."Entity-Properties"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."Kind-Properties"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert access for all users"
  on "public"."Properties"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable read access for all users"
  on "public"."Properties"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."Variables"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER entityproperty_initial_value_matches_data_type BEFORE INSERT OR UPDATE ON public."Entity-Properties" FOR EACH ROW EXECUTE FUNCTION public.validate_jsonb_value_matches_type('entityproperty_property_id', 'entityproperty_initial_value');

CREATE TRIGGER entityproperty_initial_value_matches_kind BEFORE INSERT OR UPDATE ON public."Entity-Properties" FOR EACH ROW EXECUTE FUNCTION public.validate_jsonb_key_matches_kind('entityproperty_property_id', 'entityproperty_initial_value');

CREATE TRIGGER kind_properties_validate_implication BEFORE INSERT OR UPDATE OF kindproperty_implication ON public."Kind-Properties" FOR EACH ROW EXECUTE FUNCTION public.trg_kind_properties_validate_implications();

CREATE TRIGGER kindproperty_initial_value_matches_data_type BEFORE INSERT OR UPDATE ON public."Kind-Properties" FOR EACH ROW EXECUTE FUNCTION public.validate_jsonb_value_matches_type('kindproperty_property_id', 'kindproperty_initial_value');

CREATE TRIGGER kindproperty_initial_value_matches_kind BEFORE INSERT OR UPDATE ON public."Kind-Properties" FOR EACH ROW EXECUTE FUNCTION public.validate_jsonb_key_matches_kind('kindproperty_property_id', 'kindproperty_initial_value');

CREATE TRIGGER variable_initial_value_matches_kind BEFORE INSERT OR UPDATE ON public."Variables" FOR EACH ROW EXECUTE FUNCTION public.validate_jsonb_key_matches_kind('variable_of_kind_id', 'variable_initial_value');

CREATE TRIGGER variable_initial_value_matches_type BEFORE INSERT OR UPDATE ON public."Variables" FOR EACH ROW EXECUTE FUNCTION public.validate_jsonb_value_matches_type('variable_of_kind_id', 'variable_initial_value');


