


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."ruleboook outcomes" AS ENUM (
    'no outcome',
    'success',
    'failure'
);


ALTER TYPE "public"."ruleboook outcomes" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_indefinite_article"("next_text" "text") RETURNS "text"
    LANGUAGE "sql" IMMUTABLE
    AS $$
    SELECT CASE 
        -- 2. Handle Silent 'H' edge cases (Sound like vowels -> 'an')
        WHEN lower(trim(next_text)) SIMILAR TO '(hour|honest|honor|heir)%' THEN 'an'

        -- 3. Handle Hard 'U/O' edge cases (Sound like consonants -> 'a')
        WHEN lower(trim(next_text)) SIMILAR TO '(university|unicorn|one|user)%' THEN 'a'

        -- 4. Standard Vowel rule
        WHEN lower(substring(trim(next_text) from 1 for 1)) IN ('a', 'e', 'i', 'o', 'u') THEN 'an'

        -- 5. Standard Consonant default
        ELSE 'a'
    END;
$$;


ALTER FUNCTION "public"."get_indefinite_article"("next_text" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."All Kinds" (
    "kind_id" bigint NOT NULL,
    "kind_name" "text" DEFAULT ''::"text" NOT NULL,
    "parent_kind_id" bigint,
    "kind_properties" "jsonb"
);


ALTER TABLE "public"."All Kinds" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."Kinds" WITH ("security_invoker"='on') AS
 SELECT "a"."kind_id",
    "a"."kind_name",
    "k"."kind_name" AS "parent_kind_name",
    "a"."kind_properties"
   FROM ("public"."All Kinds" "a"
     LEFT JOIN "public"."All Kinds" "k" ON (("k"."kind_id" = "a"."parent_kind_id")))
  WHERE (("a"."kind_id" >= 1) AND ("a"."kind_id" <= 499));


ALTER VIEW "public"."Kinds" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."Kinds of Value" WITH ("security_invoker"='on') AS
 SELECT "kind_id",
    "kind_name",
    "parent_kind_id",
    "kind_properties"
   FROM "public"."All Kinds"
  WHERE (("kind_id" >= 501) AND ("kind_id" <= 1000));


ALTER VIEW "public"."Kinds of Value" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Relations" (
    "relation_id" bigint NOT NULL,
    "relation_name" "text" NOT NULL,
    "relation_verb" "text"
);


ALTER TABLE "public"."Relations" OWNER TO "postgres";


ALTER TABLE "public"."Relations" ALTER COLUMN "relation_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Relations_relation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Rulebooks" (
    "rulebook_id" bigint NOT NULL,
    "rulebook_name" "text" NOT NULL,
    "rulebook_basis" bigint,
    "rulebook_result_kind" bigint,
    "rulebook_named_outcomes_success" "text"[],
    "rulebook_named_outcomes_failure" "text"[],
    "rulebook_default_outcome" "public"."ruleboook outcomes" DEFAULT 'success'::"public"."ruleboook outcomes" NOT NULL
);


ALTER TABLE "public"."Rulebooks" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."Rulebook Assertions" WITH ("security_invoker"='on') AS
 SELECT ((((((((("Rulebooks"."rulebook_name" || ' rules is '::"text") ||
        CASE
            WHEN ("Rulebooks"."rulebook_basis" IS NOT NULL) THEN ((("public"."get_indefinite_article"("k"."kind_name") || ' '::"text") || "lower"("k"."kind_name")) || ' based '::"text")
            ELSE 'a '::"text"
        END) || 'rulebook'::"text") ||
        CASE
            WHEN ("Rulebooks"."rulebook_result_kind" IS NOT NULL) THEN (((' producing '::"text" || "public"."get_indefinite_article"("k2"."kind_name")) || ' '::"text") || "lower"("k2"."kind_name"))
            ELSE ''::"text"
        END) ||
        CASE
            WHEN (("Rulebooks"."rulebook_named_outcomes_success" IS NOT NULL) OR ("Rulebooks"."rulebook_named_outcomes_failure" IS NOT NULL)) THEN ' with outcomes '::"text"
            ELSE ''::"text"
        END) ||
        CASE
            WHEN ("Rulebooks"."rulebook_named_outcomes_success" IS NOT NULL) THEN ("array_to_string"("Rulebooks"."rulebook_named_outcomes_success", ', '::"text") || ' (success)'::"text")
            ELSE ''::"text"
        END) ||
        CASE
            WHEN (("Rulebooks"."rulebook_named_outcomes_success" && "Rulebooks"."rulebook_named_outcomes_failure") IS NOT NULL) THEN ' and '::"text"
            ELSE ''::"text"
        END) ||
        CASE
            WHEN ("Rulebooks"."rulebook_named_outcomes_failure" IS NOT NULL) THEN ("array_to_string"("Rulebooks"."rulebook_named_outcomes_failure", ', '::"text") || ' (failure)'::"text")
            ELSE ''::"text"
        END) || '.'::"text") AS "rulebook_declaration",
    "Rulebooks"."rulebook_id",
    "Rulebooks"."rulebook_name",
    "Rulebooks"."rulebook_basis",
    "Rulebooks"."rulebook_result_kind",
    "Rulebooks"."rulebook_named_outcomes_success",
    "Rulebooks"."rulebook_named_outcomes_failure"
   FROM (("public"."Rulebooks"
     LEFT JOIN "public"."All Kinds" "k" ON (("k"."kind_id" = "Rulebooks"."rulebook_basis")))
     LEFT JOIN "public"."All Kinds" "k2" ON (("k2"."kind_id" = "Rulebooks"."rulebook_result_kind")));


ALTER VIEW "public"."Rulebook Assertions" OWNER TO "postgres";


ALTER TABLE "public"."Rulebooks" ALTER COLUMN "rulebook_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Rulebooks_rulebook_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."All Kinds"
    ADD CONSTRAINT "All Kinds_pkey" PRIMARY KEY ("kind_id");



ALTER TABLE ONLY "public"."Relations"
    ADD CONSTRAINT "Relations_pkey" PRIMARY KEY ("relation_id");



ALTER TABLE ONLY "public"."Rulebooks"
    ADD CONSTRAINT "Rulebooks_pkey" PRIMARY KEY ("rulebook_id");



ALTER TABLE ONLY "public"."All Kinds"
    ADD CONSTRAINT "All Kinds_parent_kind_id_fkey" FOREIGN KEY ("parent_kind_id") REFERENCES "public"."All Kinds"("kind_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Rulebooks"
    ADD CONSTRAINT "Rulebooks_rulebook_basis_fkey" FOREIGN KEY ("rulebook_basis") REFERENCES "public"."All Kinds"("kind_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Rulebooks"
    ADD CONSTRAINT "Rulebooks_rulebook_result_kind_fkey" FOREIGN KEY ("rulebook_result_kind") REFERENCES "public"."All Kinds"("kind_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE "public"."All Kinds" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable insert access for all users" ON "public"."All Kinds" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert access for all users" ON "public"."Rulebooks" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."All Kinds" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Rulebooks" FOR SELECT USING (true);



ALTER TABLE "public"."Relations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Rulebooks" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Rulebooks";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."get_indefinite_article"("next_text" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_indefinite_article"("next_text" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_indefinite_article"("next_text" "text") TO "service_role";


















GRANT ALL ON TABLE "public"."All Kinds" TO "anon";
GRANT ALL ON TABLE "public"."All Kinds" TO "authenticated";
GRANT ALL ON TABLE "public"."All Kinds" TO "service_role";



GRANT ALL ON TABLE "public"."Kinds" TO "anon";
GRANT ALL ON TABLE "public"."Kinds" TO "authenticated";
GRANT ALL ON TABLE "public"."Kinds" TO "service_role";



GRANT ALL ON TABLE "public"."Kinds of Value" TO "anon";
GRANT ALL ON TABLE "public"."Kinds of Value" TO "authenticated";
GRANT ALL ON TABLE "public"."Kinds of Value" TO "service_role";



GRANT ALL ON TABLE "public"."Relations" TO "anon";
GRANT ALL ON TABLE "public"."Relations" TO "authenticated";
GRANT ALL ON TABLE "public"."Relations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Relations_relation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Relations_relation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Relations_relation_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Rulebooks" TO "anon";
GRANT ALL ON TABLE "public"."Rulebooks" TO "authenticated";
GRANT ALL ON TABLE "public"."Rulebooks" TO "service_role";



GRANT ALL ON TABLE "public"."Rulebook Assertions" TO "anon";
GRANT ALL ON TABLE "public"."Rulebook Assertions" TO "authenticated";
GRANT ALL ON TABLE "public"."Rulebook Assertions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Rulebooks_rulebook_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Rulebooks_rulebook_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Rulebooks_rulebook_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


